### ISSUE TITLE
лабораторная 01 - Андрей Рузаев курс  j110

### ISSUE THREAD

**Issue by barracuda78** [avalon-dev-j110/laboratornaya-rabota-no1-barracuda78#1]
@AlekseiMaslakov 
Алексей Павлович, добрый вечер.
Это Андрей Рузаев.
Сперва сделал коммит в master branch.
Откатил назад и залил в ветку.
Проверьте, пожалуйста!

**Comment by AlekseiMaslakov** [comment]
Здравствуйте, @barracuda78 
Посмотрите на классы Person и Passport - явное дублирование полей.
Т.к. вы откатили изменения мастера, теперь в issue нет смысла - создавайте пул реквест, как я показывал на занятии.

**Comment by barracuda78** [comment]
Спасибо.
